### ISSUE TITLE
Issues with MEO Beacon Analysis

### ISSUE THREAD

**Issue by jrreich** [jrreich/MEO_Analysis_HTML_Interface#5]
**ToDo:**

- [ ] Add filter by Satellite capability (filter is done need gui - maybe pick a bunch for vary plot?)
- [ ] When a site is selected, get new timefirst and timelast, get meo and leo inputs and rcc outputs for that new time
- [ ] Only display "vary a value..." if Generate Histogram... is checked
- [x] Add GT (moving beacon) file upload and interpolate
- [x] Fail gracefully if no data is found
- [x] Generate Map It Feature 
- [x] Generate KML file if checked 
- [x] **Save / display other stats like Distance to MEO, MEOList, BcnID, Filters used**

**Done**
Add filters used to plot text box
Make different ranges for varying of different fields
Write all solutions to a file / change HTML to say save solutions not save stats to file
Fix MEO Input Analysis - fixed but can only select one MEOLUT currently.
